### ISSUE TITLE
EPEERINVALID react-simple-router@0.1.6 requires a peer of react@^0.13.0 but none was installed.

### ISSUE THREAD

**Issue by christhomas** [thechriswalker/react-simple-router#7]
Hi,  When I try to install this package now using npm, I get the following error, is it possible that the versioning is just not matching the react version? or is it because it's not compatible?

**Comment by thechriswalker** [comment]
This project has react as a `peerDependency` if you are using npm v3+ then peerDependencies are not automatically installed.
If you installed react as well, then you probably got a much newer version, and I haven't tested this with react >= 0.14.0.

TBH I recommend using react-router (https://github.com/rackt/react-router) instead, when I wrote this react-router was not nearly as robust and mature and wanted something quick and simple. react-router is awesome and use it in new projects - this repo being maintained only as bugs in my existing projects appear

**Comment by christhomas** [comment]
gotcha, well I'm trying to use it now, but appears to be also a lot more complicated :/

thanks for the quick reply!
